services:
  redis:
    image: redis
    # command: ["redis-server", "--bind", "redis", "--port", "7777"]
    networks:
      - webnet
  pg_db:
    container_name: "pg_db"
    image: postgres
    ports:
      - "8000:8000"
    networks:
      - webnet
    environment:
      POSTGRES_DB: timeblock_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
    command: -p 8000
  api:
    container_name: api
    image: timeblockapi:test3
    depends_on:
      - pg_db
      - redis
    ports:
      - 4000:4000
    environment:
      DB_HOST: pg_db
      REDIS_HOST: redis
    networks:
      - webnet
    command: ["./wait-for-it.sh", "pg_db:8000", "--", "node", "dist/index.js"]
networks:
  webnet: