services:
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "7777"]
  pg_db:
    container_name: "pg_db"
    image: postgres
    ports:
      - "8000:8000"
    environment:
      DB_HOST: host.docker.internal

      POSTGRES_DB: rclone2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
 